language: python
python:
  - "3.6"

cache:
  - pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig mecab mecab-ipadic-utf8 libmecab-dev

install:
  - make init

script:
  - make test
